<Project Sdk="Microsoft.NET.Sdk">

  <Import Project="../Version.props" />

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFrameworks>net8.0;net10.0;net11.0</TargetFrameworks>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <Version>$(WolfishMaiaVersion)</Version>
	<IncludeSourceRevisionInInformationalVersion>false</IncludeSourceRevisionInInformationalVersion>
	  
	<PackAsTool>true</PackAsTool>
	<PackageReadmeFile>README.md</PackageReadmeFile>
    <PackageLicenseFile>LICENSE.txt</PackageLicenseFile>
	<PackageOutputPath>./nupkg</PackageOutputPath>
	<ToolCommandName>maia</ToolCommandName>
	  
	<AllowedOutputExtensionsInPackageBuildOutputFolder>$(AllowedOutputExtensionsInPackageBuildOutputFolder);.pdb</AllowedOutputExtensionsInPackageBuildOutputFolder>
    <DebugSymbols>false</DebugSymbols>
    <DebugType>none</DebugType>
	<DebugSymbols>false</DebugSymbols>

	<PackageTags>maia;terminal;cmd;automation;tool;cli;ai;llm;chat;qwen;llama;csharp;dotnet-tool</PackageTags>  
	  
	<StartupObject>Wolfish.Maia.Program</StartupObject>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\Wolfish.ChatAgent\Wolfish.ChatAgent.csproj" />
    <ProjectReference Include="..\Wolfish.Commands\Wolfish.Commands.csproj" />
    <ProjectReference Include="..\Wolfish.Shared\Wolfish.Shared.csproj" />
  </ItemGroup>

  <ItemGroup>
	<None Include="..\README.md" Pack="true" PackagePath="\" />
	<None Include="..\LICENSE.txt" Pack="true" PackagePath="\" />
  </ItemGroup>
	
  <ItemGroup>
    <Folder Include="nupkg\" />
  </ItemGroup>
	
  <ItemGroup>
    <PackageReference Include="Microsoft.Extensions.Configuration" Version="10.0.8" />
    <PackageReference Include="Microsoft.Extensions.Configuration.Binder" Version="10.0.8" />
    <PackageReference Include="Microsoft.Extensions.Configuration.Json" Version="10.0.8" />
  </ItemGroup>

  <ItemGroup>
    <None Update="appsettings.json">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="cloudagents.json">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="TerminalCommands.json">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="Examples\TerminalCommands.Linux.json">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="Examples\AgentCommands.json">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="Examples\AutomatedScripts.json">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="Examples\TerminalCommands..Windows.json">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
  </ItemGroup>

</Project>
