name: Publicar Pacote NuGet
on:
  workflow_dispatch: # Permite que você clique em "Run workflow" manualmente na aba Actions do GitHub  
  release:
    types: [published]

jobs:
  build_and_publish:
    name: Build, Pack e Publish
    runs-on: ubuntu-latest

    steps:
      - name: Code Checkout
        uses: actions/checkout@v4
        with:
          persist-credentials: false

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: |
            8.0.x
            10.0.x
            11.0.x
          dotnet-quality: 'preview'

      - name: Restaurar dependências
        run: dotnet restore

      - name: Executar Testes
        run: dotnet test Wolfish.Tests/Wolfish.Tests.csproj -c Release --verbosity normal

      - name: Criar Pacote (Pack)
        run: dotnet pack Wolfish.Maia/Wolfish.Maia.csproj -c Release --output ./nupkg

      - name: Enviar Pacote (Push)
        # O GitHub injeta a chave de API salva com total segurança aqui
        env:
          NUGET_TOKEN: ${{ secrets.NUGET_API_KEY }}
        run: |
          dotnet nuget push ./nupkg/*.nupkg --source https://api.nuget.org/v3/index.json --api-key "$NUGET_TOKEN" --skip-duplicate
